# NanoMQ broker configuration
# TCP listener (used by mqtt-tcp-c protocol)
listeners.tcp {
    bind = "0.0.0.0:1883"
}

# QUIC listener (used by mqtt-quic protocol)
listeners.quic {
    bind = "0.0.0.0:14567"
    keyfile = "/etc/certs/key.pem"
    certfile = "/etc/certs/cert.pem"
}

log {
    to = [console]
    level = debug
}
