# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x06\x63\x61mpus\"\x1f\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\x1e\n\x0bRegisterAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\"A\n\x07\x43ommand\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x12\n\nts_edge_ns\x18\x03 \x01(\x03\"Y\n\nCommandAck\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0cts_device_ns\x18\x03 \x01(\x03\x12\x12\n\nts_edge_ns\x18\x04 \x01(\x03\x32~\n\rDeviceService\x12\x33\n\x08Register\x12\x12.campus.DeviceInfo\x1a\x13.campus.RegisterAck\x12\x38\n\rCommandStream\x12\x12.campus.CommandAck\x1a\x0f.campus.Command(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEINFO']._serialized_start=24
  _globals['_DEVICEINFO']._serialized_end=55
  _globals['_REGISTERACK']._serialized_start=57
  _globals['_REGISTERACK']._serialized_end=87
  _globals['_COMMAND']._serialized_start=89
  _globals['_COMMAND']._serialized_end=154
  _globals['_COMMANDACK']._serialized_start=156
  _globals['_COMMANDACK']._serialized_end=245
  _globals['_DEVICESERVICE']._serialized_start=247
  _globals['_DEVICESERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
