FROM louisroyer/ueransim-ue:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip && \
    pip3 install --no-cache-dir --break-system-packages grpcio protobuf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
